apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-producer-config
  labels:
    app: kafka-producer
data:
  KAFKA_BOOTSTRAP_SERVERS: kafkacluster-kafka-bootstrap:9092
  PRODUCER_TICK_FREQUENCY: "2000"
