apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kafka.strimzi.io/v1beta2","kind":"KafkaConnector","metadata":{"annotations":{},"labels":{"strimzi.io/cluster":"my-connect-cluster"},"name":"inventory-connector","namespace":"kafka-dev"},"spec":{"class":"io.debezium.connector.postgresql.PostgresConnector","config":{"database.dbname":"postgres","database.hostname":"postgres.demo-rhaf.svc","database.password":"postgres","database.port":5432,"database.server.name":"inventory","database.user":"postgres"},"tasksMax":1}}
  labels:
    strimzi.io/cluster: my-connect-cluster1
  name: my-kafka-connector
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  config:
    database.dbname: postgres
    database.hostname: postgres.cdc-demo.svc
    database.password: postgres
    database.port: 5432
    database.server.name: inventory
    database.user: postgres
    table.blacklist: 'inventory.products_on_hand, products_on_hand'
  tasksMax: 1
