apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kafka.strimzi.io/v1beta2","kind":"KafkaUser","metadata":{"annotations":{},"labels":{"strimzi.io/cluster":"my-cluster"},"name":"debezium-user","namespace":"kafka-dev"},"spec":{"authentication":{"type":"scram-sha-512"},"authorization":{"acls":[{"host":"*","operation":"Describe","resource":{"name":"*","patternType":"literal","type":"topic"}},{"host":"*","operation":"Write","resource":{"name":"*","patternType":"literal","type":"topic"}},{"host":"*","operation":"Create","resource":{"name":"*","patternType":"literal","type":"topic"}},{"host":"*","operation":"Read","resource":{"name":"*","patternType":"literal","type":"topic"}}],"type":"simple"}}}
  labels:
    strimzi.io/cluster: my-cluster
  name: debezium-user
  namespace: kafka-dev
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
    - host: '*'
      operation: Describe
      resource:
        name: '*'
        patternType: literal
        type: topic
    - host: '*'
      operation: Write
      resource:
        name: '*'
        patternType: literal
        type: topic
    - host: '*'
      operation: Create
      resource:
        name: '*'
        patternType: literal
        type: topic
    - host: '*'
      operation: Read
      resource:
        name: '*'
        patternType: literal
        type: topic
    - host: '*'
      operation: Read
      resource:
        name: '*'
        patternType: literal
        type: group
    type: simple
